### ISSUE TITLE
JSTOR dfr and Paper Machines

### ISSUE THREAD

**Issue by brekhusr** [papermachines/papermachines#41]
I see that in your development of Paper Machines you included a data set from JSTOR DFR.  I'm wondering how you were able to do that.  I requested a couple data sets from JSTOR DFR, csv format (was that the right choice?) but it looks like, instead of full text, they have links to full text in one of the fields.

Two questions:
1) how do I import the csv file into Zotero, or should I request XML instead?  How would I import that set of records into Zotero?
2) will Zotero pull the full text automatically from JSTOR or are there additional steps needed to give Paper Machines some actual text to analyze?

**Comment by sdspieg** [comment]
I have finally managed to get sthg out of JSTOR dfr and into pm. But when I try to run the topicmodelling, I get the following error (and please note the double instead of single) backward slashes in the last line. Does anybody know how to fix this? Thanks!

INFO:root:command: C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet_lda_jstor.py C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\args\ba119f37.json
INFO:root:copying texts into single file
ERROR:root:Traceback (most recent call last):
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet_lda_jstor.py", line 48, in 
    processor.process()
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet_lda.py", line 51, in process
    self._setup_mallet_instances(sequence=True, tfidf=self.tfidf,
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet.py", line 295, in _setup_mallet_instances
    self._import_texts()
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet.py", line 267, in _import_texts
    self._import_files()
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet.py", line 135, in _import_files
    for (doi, text) in self._import_dfr(self.dfr_dir):
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet.py", line 51, in _import_dfr
    citations = self._import_dfr_metadata(dfr_dir)
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\mallet.py", line 38, in _import_dfr_metadata
    for rowdict in self.parse_csv(citation_file):
  File "C:\Users\Stephan\AppData\Roaming\Mozilla\Firefox\Profiles\alqrttem.default\zotero\papermachines\processors\textprocessor.py", line 0, in parse_csv
IOError: [Errno 2] No such file or directory: u'C:\\Users\\Stephan\\AppData\\Roaming\\Mozilla\\Firefox\\Profiles\\alqrttem.default\\zotero\\papermachines\\out\\2015.4.4.Cqgq64dD\\citations.CSV'
