### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by duncdrum** [papermachines/papermachines#55]
One of my zotero collections is giving me the following trouble; all otheres work fine:
I believe that the file/directory in questino was created by doing an automated lookup for the pdf upon importing into zotero. however the reference that was automatically generated turned out to be false and had to be edited by hand. 

Is there a way to get rid of this, or even better can papermachine be made to throw an exception for the missing item instead breaking down? Or even better look for the proper file directory associated with the reference in question?

Any suggestions welcome. 

INFO:root:command: /Users/XXX/Library/Application\ Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/wordcloud_large.py /Users/XXX/Library/Application\ Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/args/bd86a91.json
INFO:root:starting to process
INFO:root:finding word frequencies
INFO:root:processing /Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/C159/Livingstone_-_2003_-_Ch.1_A_Geography_of_Science.txt
INFO:root:processing /Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/C159/Revel_-_1995_-_Microanalysis_and_the_Construction_of_the_Social.txt
ERROR:root:Traceback (most recent call last):
  File "/Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/wordcloud_large.py", line 30, in 
    processor.process()
  File "/Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/wordcloud.py", line 123, in process
    freqs = self._findWordFreqs(self.files)
  File "/Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/wordcloud.py", line 106, in _findWordFreqs
    freqs.update(self.getNgrams(filename,
  File "/Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/textprocessor.py", line 216, in getNgrams
    freqs = Counter()
  File "/Users/XXX/Library/Application Support/Firefox/Profiles/sklfgs3h.default/zotero/papermachines/processors/jython.jar/Lib/codecs.py", line 881, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'How actors macro-structure reality and how sociologists help them to do so'

OS X 10.9.3 FF29.0.1 MLZ 4.0.20m451 PM 0.4.8 java 1.7.0_55

**Comment by swami89** [comment]
Hi Chris, 
I think I am facing a similar problem

OS X El Capitan Version 10.11.15

java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b14, mixed mode)

Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 26 2016, 12:10:39) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

When I use flight paths feature of papermachine I am getting this message can you please help. 

The process log is displayed below. Refreshing status in 15 seconds.
INFO:root:command: /Users/Swamy/Library/Application\ Support/Firefox/Profiles/ielhwv9h.default/zotero/papermachines/processors/geoparser_flightpaths.py /Users/Swamy/Library/Application\ Support/Firefox/Profiles/ielhwv9h.default/zotero/papermachines/args/c2266664.json
ERROR:root:Traceback (most recent call last):
  File "/Users/Swamy/Library/Application Support/Firefox/Profiles/ielhwv9h.default/zotero/papermachines/processors/geoparser_flightpaths.py", line 164, in 
    processor.process()
  File "/Users/Swamy/Library/Application Support/Firefox/Profiles/ielhwv9h.default/zotero/papermachines/processors/geoparser_flightpaths.py", line 148, in process
    params = {
ValueError: min of empty sequence
